# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'
use_modular_headers!
inhibit_all_warnings!
...
pre_install do |installer|
    remove_swiftui()
end

def remove_swiftui
  # 解决 xcode13 Release模式下SwiftUI报错问题
  system("rm -rf ./Pods/Kingfisher/Sources/SwiftUI")
  code_file = "./Pods/Kingfisher/Sources/General/KFOptionsSetter.swift"
  code_text = File.read(code_file)
  code_text.gsub!(/#if canImport\(SwiftUI\) \&\& canImport\(Combine\)(.|\n)+#endif/,'')
  system("rm -rf " + code_file)
  aFile = File.new(code_file, 'w+')
  aFile.syswrite(code_text)
  aFile.close()
end

target 'GameFi' do
  use_frameworks!
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod "ESTabBarController-swift"
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'MCToast'
  pod 'Bugly'
#  pod 'EmptyKit'
  pod 'JXWebViewController'
end
