# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameFi' do
  use_frameworks!
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod "ESTabBarController-swift"
end
