
platform :ios, '11.0'

target 'GameFi' do
  use_frameworks!
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod "ESTabBarController-swift"
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'MCToast'
  pod 'JXWebViewController'
  pod 'AttributedString'
end
